nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173', 'http://localhost:4173']  # Ton domaine frontend
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173', 'http://localhost:4173']
            allow_headers: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
